version: "2"
services:
  ploneapi:
    image: bmeugis/clms.downloadtool:1.0
    ports:
      - 62934:8080
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:3000,http://127.0.0.1:3000"
    depends_on:
      - memcached
    volumes:
      - data:/data
      - app:/plone/instance/src/clms.downloadtool/
  memcached:
    image: memcached
    command:
      - "-m"
      - "512"
volumes:
  data:
    driver: local
